### ISSUE TITLE
Serial monitor on Adafruit M0 feather 

### ISSUE THREAD

**Issue by SCengineer** [u-fire/ISE_Probe#3] opened 2018-08-19 17:34 UTC
I'm using an Adafruit Feather M0 wifi with ATWINC1500 (SAMD core) with your pH probe module. The problem is I can't get the serial monitor to work after setting up the ISE_ph class. Everything compiles and uploads fine but the COM port simply doesn't show up (error: Board at COMx is not available). Everything works fine on a MEGA 2560. I understand Adafruit has modified the official SAMD core in regards to serial debug which might be part of the issue. Any help would be appreciated.

**Comment by justind000** [comment] 2018-08-19 17:42
Since you have confirmed the hardware is working on your 2560 board, it is safe to say that this isn't a hardware issue. The ISE_pH class doesn't make any use of Serial, so I suspect it isn't a software issue either. 
I don't have a Feather M0 to experiment with, so I can't be much help I'm afraid. Are you having this issue with all sketches for the Feather? A quick search of the internet mentions what you said, that the core is different (https://learn.adafruit.com/adafruit-feather-m0-basic-proto/adapting-sketches-to-m0), so a guess would be it has something to do with that. Let me know how it goes.

**Comment by SCengineer** [comment] 2018-08-21 04:03
The serial monitor is working with other Feather sketches. Normally I get the Feather to program on COM6 and when its finished, it switches to COM5 where I can use the serial monitor. For whatever reason when I initialize your code: 
```
#include <ISE_pH.h>
ISE_pH ph;

```
It compiles and uploads fine but COM5 isn't found after programming. It also doesn't automatically get back into bootloader mode when I try and program it again. I suspect something is going weird with communication over the USB in general, not just the serial over the USB. I'll let you know if I figure anything out. These Feather boards are definitely more finicky then the standard boards.

**Comment by justind000** [comment] 2018-08-21 04:33
Not sure about it, but maybe it has something to do with ISE_pH including <math.h>, <Arduino.h>, and <Wire.h>? Maybe it's pulling in a different core's header files?

**Comment by justind000** [comment] 2018-08-24 20:56
A posted on the EC_Salinity board's related issue. Let me know if you run into any trouble applying this to the pH library. But you basically just use it exactly the same, with the minor initialization changes and arrow notation. 

So I got an Adafruit Feather M0 to try this with and got it working without any change to the library, although there will need to be a change in the future. 

The TLDR version is you just need to use arrow notation to access the class members. 

```
#include <ECSalinity.h>

EC_Salinity *ec;

void setup() {
  ec = new EC_Salinity(0x3c);
  Serial.begin(9600);

  while (!Serial);
  Serial.println(ec->getVersion(), HEX);
}

void loop() {}
```
I don't know enough about the M0 to guess why it doesn't like the Wire library initialization in the class initialization. My first thoughts on a good permanent fix for this are to include a ::begin() method like most Arduino-type libraries have. I just wanted to let you know how to get some use out of it as-is for now though.

**Closed** 2018-09-10 06:54 UTC
Labels: compatibility
